codepkg/objects/Error_Log__c.object
<CustomObject>
    <description>Configuration Object</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DML_Field_Names__c</fullName>
        <label>DML Field Names</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DML_Id__c</fullName>
        <label>DML Id</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DML_Message__c</fullName>
        <label>DML Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DML_Num__c</fullName>
        <label>DML Number of Failed Rows</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DML_Type__c</fullName>
        <label>DML Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <picklist>
            <picklistValues>
                <fullName>Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diagnostic</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Exception_Cause__c</fullName>
        <label>Exception Cause</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Line_Number__c</fullName>
        <label>Exception Line Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Stack_Trace_String__c</fullName>
        <label>Exception Stack Trace String</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <label>Exception Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Id_Type__c</fullName>
        <label>Id Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Sandbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Sandbox?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Send_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Error Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/classes/MSH_ErrorLogger.cls
/**
 * This class writes error and success logs to the Error Log object.
 *
 * @author Varun Reddy Penna
 * @version
 */
global without sharing class MSH_ErrorLogger {

  private String objName;
  private static Boolean isSandbox;
  @testVisible
  private List<Error_Log__c> logs;

  /**
   * TODO Description
   *
   * @param objName, TODO Description
   */
  global MSH_ErrorLogger (Object objName) {
   logs = new List <Error_Log__c> ();
   this.objName = String.valueOf(objName);
  }

  /**
   * TODO Description
   *
   * @param msg, TODO Description
   */
  global void logErrorMessage (String msg) {
    logErrorMessage (msg, Userinfo.getUserId());
  }

  /**
   * TODO Description
   *
   * @param msg, TODO Description
   * @param recordId, TODO Description
   */
  global void logErrorMessage (String msg, String recordId) {
    Id recId = String.isEmpty(recordId) ? null : Id.valueOf(recordId);
    Error_Log__c msgLog = new Error_Log__c();
    msgLog.Message__c = msg == null ? '' : msg;
    msgLog.Event_Type__c = 'Diagnostic';
    msgLog.Record_Id__c = recordId == null ? '' : recordId;
    msgLog.Id_Type__c = recordId == null ? '' : recId.getSObjectType().getDescribe().getName();
    msgLog.Class_Name__c = objName;
    msgLog.Is_Sandbox__c = isSandbox;
    logs.add(msgLog);
  }

  /**
   * TODO Description
   *
   * @param ex, TODO Description
   */
  global void logException (Exception ex){
    logException(ex, null);
  }

  /**
   * TODO Description
   *
   * @param ex, TODO Description
   * @param recordId, TODO Description
   */
  global void logException (Exception ex, String recordId) {
    if(MSH_RecursiveTriggerHandler.isSandboxQuery == true) {
      isSandbox = [Select isSandbox From Organization Limit 1].isSandbox;
      MSH_RecursiveTriggerHandler.isSandboxQuery = false;
    }
    Id recId = String.isEmpty(recordId) ? null : Id.valueOf(recordId);
    if (ex != null) {
      Error_Log__c errorLog = new Error_Log__c();
      errorLog.Message__c = ex.getMessage();
      errorLog.Exception_Cause__c = '' + ex.getCause();
      errorLog.Exception_Type__c = ex.getTypeName();
      if (ex.getTypeName() == 'System.DMLException') {
        Integer numErrors = ex.getNumDml();
        errorLog.DML_Num__c = numErrors;
        for (Integer i=0; i<numErrors; i++) {
          errorLog.DML_Field_Names__c += ex.getDmlFieldNames(i);
          errorLog.DML_Message__c += ex.getDmlMessage(i);
          errorLog.DML_Id__c += ex.getDmlId(i);
          errorLog.DML_Type__c += ex.getDmlType(i);
        }
      }
      errorLog.Exception_Line_Number__c = String.valueOf(ex.getLineNumber());
      errorLog.Exception_Stack_Trace_String__c = ex.getStackTraceString();
      errorLog.Event_Type__c = 'Diagnostic';
      errorLog.Record_Id__c = recordId == null ? UserInfo.getUserId() : recordId;
      errorLog.Id_Type__c = recordId == null ? 'User' : recId.getSObjectType().getDescribe().getName();
      errorLog.Class_Name__c = objName;
      errorLog.Is_Sandbox__c = isSandbox;
      errorLog.Send_Email__c = true;
      logs.add(errorLog);
    }
  }

  /**
   * TODO Description
   */
  global void saveAllLogs () {
    if (!logs.isEmpty()) {
      try {
        if (System.isFuture() || System.isBatch()) {
          // Never throw a governor exception while trying to save error log records.
          if (shouldThisBeSaved (logs.size())) {
            Database.DMLOptions dml = new Database.DMLOptions();
            dml.allowFieldTruncation = true;
            Database.insert(logs, dml);
          }
          else {
            System.debug('+++++++++ ErrorLog is hitting DML limits');
          }
        }
        else {
          System.debug(LoggingLevel.INFO, 'Sending to the queueable...');
          MSH_ErrorLoggerQueueable aq = new MSH_ErrorLoggerQueueable(logs);
          ID jobID = System.enqueueJob(aq);
        }
      } catch (Exception ex) {
        System.debug('+++++++++ ErrorLog error: ' + ex);
      }
    }
  }

  /**
   * TODO Description
   *
   * @param logSize, TODO Description
   * @return TODO Description
   */
  public static Boolean shouldThisBeSaved (Integer logSize) {
    return (Limits.getLimitDMLStatements() - Limits.getDMLStatements()) > 0
                &&(Limits.getLimitDMLRows() - Limits.GetDMLRows()) > logSize;
  }
}